CREATE TABLE `tlht_amazon_jobs` (
                          `order_created_time` datetime_interval_code
                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

[0] => ORDER_CREATED_TIME
[1] => SERVICE_ORDER_ID
[2] => JOB_ID
[3] => SERVICE_ASIN
[4] => JOB_NAME
[5] => JOB_STATUS
[6] => APPOINTMENT_DATE
[7] => APPOINTMENT_START_TIME
[8] => APPOINTMENT_END_TIME
[9] => PRODUCT_ORDER_ID
[10] => PRODUCT_ASIN
[11] => PRODUCT_NAME
[12] => PRODUCT_QUANTITY_PURCHASED
[13] => PRODUCT_ORDER_STATUS
[14] => TECHNICIAN
[15] => BUYER_PHONE_NUMBER
[16] => SHIP_ADDRESS_LINE_1
[17] => SHIP_ADDRESS_LINE_2
[18] => SHIP_POSTAL_CODE
[19] => SHIP_CITY
[20] => COVERAGE_AREA
[21] => BUYER_ID
[22] => DEFECT